export const randomSaying = [{
  id : 1,
  random : '삶이 있는 한 희망은 있다',
  name : '키케로'
},
{ id : 2,
  random : '하루에 3시간을 걸으면 7년 후에 지구를 한바퀴 돌 수 있다',
name : 'ddd'},
{ id : 3,
  random : 'ddddd',
name : 'sqweqwe'},
{ id : 2,
  random : '하루에 3시간을 걸으면 7년 후에 지구를 한바퀴 돌 수 있다',
name : 'ddd'},
{ id : 2,
  random : '하루에 3시간을 걸으면 7년 후에 지구를 한바퀴 돌 수 있다',
name : 'ddd'},
{ id : 2,
  random : '하루에 3시간을 걸으면 7년 후에 지구를 한바퀴 돌 수 있다',
name : 'ddd'},
{ id : 2,
  random : '하루에 3시간을 걸으면 7년 후에 지구를 한바퀴 돌 수 있다',
name : 'ddd'},
{ id : 2,
  random : '하루에 3시간을 걸으면 7년 후에 지구를 한바퀴 돌 수 있다',
name : 'ddd'},
{ id : 2,
  random : '하루에 3시간을 걸으면 7년 후에 지구를 한바퀴 돌 수 있다',
name : 'ddd'},
{ id : 2,
  random : '하루에 3시간을 걸으면 7년 후에 지구를 한바퀴 돌 수 있다',
name : 'ddd'},
{ id : 2,
  random : '하루에 3시간을 걸으면 7년 후에 지구를 한바퀴 돌 수 있다',
name : 'ddd'},
{ id : 2,
  random : '하루에 3시간을 걸으면 7년 후에 지구를 한바퀴 돌 수 있다',
name : 'ddd'},
{ id : 2,
  random : '하루에 3시간을 걸으면 7년 후에 지구를 한바퀴 돌 수 있다',
name : 'ddd'},
{ id : 2,
  random : '일하는 시간과 노는 시간을 뚜렷이 구분하라 . 시간의 중요성을 이해하고 매순간을 즐겁게 보내고 유용하게 활용하라. 그러면 젋은 날은 유쾌함으로 가득찰것이고 늙어서도 후회할 일이 적어질것이며 비록 가난할 때라도 인생을 아름답게 살아갈수있다',
name : 'ddd'},

]

export const userinfo = {
  name : '장태성',
  email : 'dadadaca@naver.com'
}